/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BeneficiaryRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveBeneficiary"
      | "approved"
      | "metaCID"
      | "owner"
      | "registerBeneficiary"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BeneficiaryApproved" | "BeneficiaryRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveBeneficiary",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "approved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "metaCID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBeneficiary",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metaCID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBeneficiary",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryApprovedEvent {
  export type InputTuple = [beneficiary: AddressLike, approved: boolean];
  export type OutputTuple = [beneficiary: string, approved: boolean];
  export interface OutputObject {
    beneficiary: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryRegisteredEvent {
  export type InputTuple = [beneficiary: AddressLike, metaCID: string];
  export type OutputTuple = [beneficiary: string, metaCID: string];
  export interface OutputObject {
    beneficiary: string;
    metaCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BeneficiaryRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BeneficiaryRegistry;
  waitForDeployment(): Promise<this>;

  interface: BeneficiaryRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike, isApproved: boolean],
    [void],
    "nonpayable"
  >;

  approved: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  metaCID: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike, _metaCID: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveBeneficiary"
  ): TypedContractMethod<
    [beneficiary: AddressLike, isApproved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approved"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "metaCID"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBeneficiary"
  ): TypedContractMethod<
    [beneficiary: AddressLike, _metaCID: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BeneficiaryApproved"
  ): TypedContractEvent<
    BeneficiaryApprovedEvent.InputTuple,
    BeneficiaryApprovedEvent.OutputTuple,
    BeneficiaryApprovedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryRegistered"
  ): TypedContractEvent<
    BeneficiaryRegisteredEvent.InputTuple,
    BeneficiaryRegisteredEvent.OutputTuple,
    BeneficiaryRegisteredEvent.OutputObject
  >;

  filters: {
    "BeneficiaryApproved(address,bool)": TypedContractEvent<
      BeneficiaryApprovedEvent.InputTuple,
      BeneficiaryApprovedEvent.OutputTuple,
      BeneficiaryApprovedEvent.OutputObject
    >;
    BeneficiaryApproved: TypedContractEvent<
      BeneficiaryApprovedEvent.InputTuple,
      BeneficiaryApprovedEvent.OutputTuple,
      BeneficiaryApprovedEvent.OutputObject
    >;

    "BeneficiaryRegistered(address,string)": TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;
    BeneficiaryRegistered: TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;
  };
}
