/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CrisisCouncilInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abandon"
      | "againstWeight"
      | "castVote"
      | "closeEarly"
      | "emergencyVotingPeriod"
      | "executeResolution"
      | "finalizeOutcome"
      | "getEncryptedTallies"
      | "grantDecryption"
      | "nextResolutionId"
      | "normalVotingPeriod"
      | "owner"
      | "passRatioBps"
      | "protocolId"
      | "quorum"
      | "resolutions"
      | "setParams"
      | "submitResolution"
      | "supportWeight"
      | "treasury"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OutcomeFinalized"
      | "ResolutionSubmitted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "abandon",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "againstWeight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeEarly",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyVotingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeOutcome",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTallies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDecryption",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextResolutionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "normalVotingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "passRatioBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "quorum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolutions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResolution",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportWeight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "abandon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "againstWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeEarly", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTallies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextResolutionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "normalVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "passRatioBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace OutcomeFinalizedEvent {
  export type InputTuple = [id: BigNumberish, status: BigNumberish];
  export type OutputTuple = [id: bigint, status: bigint];
  export interface OutputObject {
    id: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    proposer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    emergency: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    proposer: string,
    recipient: string,
    amount: bigint,
    emergency: boolean
  ];
  export interface OutputObject {
    id: bigint;
    proposer: string;
    recipient: string;
    amount: bigint;
    emergency: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    id: BigNumberish,
    voter: AddressLike,
    support: boolean,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    voter: string,
    support: boolean,
    weight: bigint
  ];
  export interface OutputObject {
    id: bigint;
    voter: string;
    support: boolean;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrisisCouncil extends BaseContract {
  connect(runner?: ContractRunner | null): CrisisCouncil;
  waitForDeployment(): Promise<this>;

  interface: CrisisCouncilInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abandon: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  againstWeight: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  castVote: TypedContractMethod<
    [
      id: BigNumberish,
      support: boolean,
      oneExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  closeEarly: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  emergencyVotingPeriod: TypedContractMethod<[], [bigint], "view">;

  executeResolution: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeOutcome: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedTallies: TypedContractMethod<
    [id: BigNumberish],
    [[string, string] & { encSupport: string; encAgainst: string }],
    "view"
  >;

  grantDecryption: TypedContractMethod<
    [id: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  nextResolutionId: TypedContractMethod<[], [bigint], "view">;

  normalVotingPeriod: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  passRatioBps: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  quorum: TypedContractMethod<[], [bigint], "view">;

  resolutions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        proposer: string;
        recipient: string;
        token: string;
        amount: bigint;
        purposeCID: string;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        emergency: boolean;
        fromCrisisPool: boolean;
      }
    ],
    "view"
  >;

  setParams: TypedContractMethod<
    [
      _quorum: BigNumberish,
      _passRatioBps: BigNumberish,
      _normal: BigNumberish,
      _emergency: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitResolution: TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      purposeCID: string,
      duration: BigNumberish,
      emergency: boolean,
      fromCrisisPool: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  supportWeight: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, boolean] & { support: boolean; voted: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abandon"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "againstWeight"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      support: boolean,
      oneExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeEarly"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyVotingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeResolution"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeOutcome"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedTallies"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[string, string] & { encSupport: string; encAgainst: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantDecryption"
  ): TypedContractMethod<
    [id: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextResolutionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "normalVotingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "passRatioBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolutions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        proposer: string;
        recipient: string;
        token: string;
        amount: bigint;
        purposeCID: string;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        emergency: boolean;
        fromCrisisPool: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setParams"
  ): TypedContractMethod<
    [
      _quorum: BigNumberish,
      _passRatioBps: BigNumberish,
      _normal: BigNumberish,
      _emergency: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResolution"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      purposeCID: string,
      duration: BigNumberish,
      emergency: boolean,
      fromCrisisPool: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportWeight"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, boolean] & { support: boolean; voted: boolean }],
    "view"
  >;

  getEvent(
    key: "OutcomeFinalized"
  ): TypedContractEvent<
    OutcomeFinalizedEvent.InputTuple,
    OutcomeFinalizedEvent.OutputTuple,
    OutcomeFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionSubmitted"
  ): TypedContractEvent<
    ResolutionSubmittedEvent.InputTuple,
    ResolutionSubmittedEvent.OutputTuple,
    ResolutionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "OutcomeFinalized(uint256,uint8)": TypedContractEvent<
      OutcomeFinalizedEvent.InputTuple,
      OutcomeFinalizedEvent.OutputTuple,
      OutcomeFinalizedEvent.OutputObject
    >;
    OutcomeFinalized: TypedContractEvent<
      OutcomeFinalizedEvent.InputTuple,
      OutcomeFinalizedEvent.OutputTuple,
      OutcomeFinalizedEvent.OutputObject
    >;

    "ResolutionSubmitted(uint256,address,address,uint256,bool)": TypedContractEvent<
      ResolutionSubmittedEvent.InputTuple,
      ResolutionSubmittedEvent.OutputTuple,
      ResolutionSubmittedEvent.OutputObject
    >;
    ResolutionSubmitted: TypedContractEvent<
      ResolutionSubmittedEvent.InputTuple,
      ResolutionSubmittedEvent.OutputTuple,
      ResolutionSubmittedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
