/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToEmergencyTotal"
      | "addToNormalTotal"
      | "getEncryptedEmergencyTotal"
      | "getEncryptedNormalTotal"
      | "getEncryptedUserNote"
      | "protocolId"
      | "setMyEncryptedNote"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addToEmergencyTotal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToNormalTotal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEmergencyTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedNormalTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedUserNote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMyEncryptedNote",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToEmergencyTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToNormalTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEmergencyTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedNormalTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedUserNote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMyEncryptedNote",
    data: BytesLike
  ): Result;
}

export interface FHEVault extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVault;
  waitForDeployment(): Promise<this>;

  interface: FHEVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToEmergencyTotal: TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  addToNormalTotal: TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedEmergencyTotal: TypedContractMethod<[], [string], "view">;

  getEncryptedNormalTotal: TypedContractMethod<[], [string], "view">;

  getEncryptedUserNote: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setMyEncryptedNote: TypedContractMethod<
    [noteExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToEmergencyTotal"
  ): TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addToNormalTotal"
  ): TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedEmergencyTotal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedNormalTotal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedUserNote"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMyEncryptedNote"
  ): TypedContractMethod<
    [noteExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
