/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RecipientDirectoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approved"
      | "enrollRecipient"
      | "owner"
      | "profileCID"
      | "updateRecipientApproval"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RecipientApprovalUpdated" | "RecipientEnrolled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enrollRecipient",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profileCID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRecipientApproval",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "approved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enrollRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profileCID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRecipientApproval",
    data: BytesLike
  ): Result;
}

export namespace RecipientApprovalUpdatedEvent {
  export type InputTuple = [recipient: AddressLike, approved: boolean];
  export type OutputTuple = [recipient: string, approved: boolean];
  export interface OutputObject {
    recipient: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientEnrolledEvent {
  export type InputTuple = [recipient: AddressLike, profileCID: string];
  export type OutputTuple = [recipient: string, profileCID: string];
  export interface OutputObject {
    recipient: string;
    profileCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RecipientDirectory extends BaseContract {
  connect(runner?: ContractRunner | null): RecipientDirectory;
  waitForDeployment(): Promise<this>;

  interface: RecipientDirectoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approved: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  enrollRecipient: TypedContractMethod<
    [recipient: AddressLike, _profileCID: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  profileCID: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  updateRecipientApproval: TypedContractMethod<
    [recipient: AddressLike, isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approved"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "enrollRecipient"
  ): TypedContractMethod<
    [recipient: AddressLike, _profileCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profileCID"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "updateRecipientApproval"
  ): TypedContractMethod<
    [recipient: AddressLike, isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RecipientApprovalUpdated"
  ): TypedContractEvent<
    RecipientApprovalUpdatedEvent.InputTuple,
    RecipientApprovalUpdatedEvent.OutputTuple,
    RecipientApprovalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientEnrolled"
  ): TypedContractEvent<
    RecipientEnrolledEvent.InputTuple,
    RecipientEnrolledEvent.OutputTuple,
    RecipientEnrolledEvent.OutputObject
  >;

  filters: {
    "RecipientApprovalUpdated(address,bool)": TypedContractEvent<
      RecipientApprovalUpdatedEvent.InputTuple,
      RecipientApprovalUpdatedEvent.OutputTuple,
      RecipientApprovalUpdatedEvent.OutputObject
    >;
    RecipientApprovalUpdated: TypedContractEvent<
      RecipientApprovalUpdatedEvent.InputTuple,
      RecipientApprovalUpdatedEvent.OutputTuple,
      RecipientApprovalUpdatedEvent.OutputObject
    >;

    "RecipientEnrolled(address,string)": TypedContractEvent<
      RecipientEnrolledEvent.InputTuple,
      RecipientEnrolledEvent.OutputTuple,
      RecipientEnrolledEvent.OutputObject
    >;
    RecipientEnrolled: TypedContractEvent<
      RecipientEnrolledEvent.InputTuple,
      RecipientEnrolledEvent.OutputTuple,
      RecipientEnrolledEvent.OutputObject
    >;
  };
}
