/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReliefTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balances"
      | "contribute"
      | "council"
      | "crisisBalances"
      | "disburseTo"
      | "owner"
      | "pause"
      | "paused"
      | "queryBalances"
      | "setCouncil"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionReceived"
      | "CouncilUpdated"
      | "FundsSent"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "council", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "crisisBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseTo",
    values: [AddressLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "queryBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCouncil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "council", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "crisisBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disburseTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCouncil", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    crisis: boolean
  ];
  export type OutputTuple = [
    contributor: string,
    token: string,
    amount: bigint,
    crisis: boolean
  ];
  export interface OutputObject {
    contributor: string;
    token: string;
    amount: bigint;
    crisis: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouncilUpdatedEvent {
  export type InputTuple = [council: AddressLike];
  export type OutputTuple = [council: string];
  export interface OutputObject {
    council: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsSentEvent {
  export type InputTuple = [
    token: AddressLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReliefTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): ReliefTreasury;
  waitForDeployment(): Promise<this>;

  interface: ReliefTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  contribute: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, crisis: boolean],
    [void],
    "payable"
  >;

  council: TypedContractMethod<[], [string], "view">;

  crisisBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  disburseTo: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      fromCrisis: boolean
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  queryBalances: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { normal: bigint; crisis: bigint }],
    "view"
  >;

  setCouncil: TypedContractMethod<
    [_council: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, crisis: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "council"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "crisisBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "disburseTo"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      fromCrisis: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "queryBalances"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { normal: bigint; crisis: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCouncil"
  ): TypedContractMethod<[_council: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "CouncilUpdated"
  ): TypedContractEvent<
    CouncilUpdatedEvent.InputTuple,
    CouncilUpdatedEvent.OutputTuple,
    CouncilUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsSent"
  ): TypedContractEvent<
    FundsSentEvent.InputTuple,
    FundsSentEvent.OutputTuple,
    FundsSentEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ContributionReceived(address,address,uint256,bool)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "CouncilUpdated(address)": TypedContractEvent<
      CouncilUpdatedEvent.InputTuple,
      CouncilUpdatedEvent.OutputTuple,
      CouncilUpdatedEvent.OutputObject
    >;
    CouncilUpdated: TypedContractEvent<
      CouncilUpdatedEvent.InputTuple,
      CouncilUpdatedEvent.OutputTuple,
      CouncilUpdatedEvent.OutputObject
    >;

    "FundsSent(address,address,uint256)": TypedContractEvent<
      FundsSentEvent.InputTuple,
      FundsSentEvent.OutputTuple,
      FundsSentEvent.OutputObject
    >;
    FundsSent: TypedContractEvent<
      FundsSentEvent.InputTuple,
      FundsSentEvent.OutputTuple,
      FundsSentEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
