/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShieldedReliefVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accumulateCrisis"
      | "accumulateStandard"
      | "protocolId"
      | "saveMyEncryptedMemo"
      | "viewEncryptedCrisisTotal"
      | "viewEncryptedStandardTotal"
      | "viewEncryptedUserMemo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accumulateCrisis",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "accumulateStandard",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saveMyEncryptedMemo",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedCrisisTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedStandardTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedUserMemo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulateCrisis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulateStandard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saveMyEncryptedMemo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedCrisisTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedStandardTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedUserMemo",
    data: BytesLike
  ): Result;
}

export interface ShieldedReliefVault extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldedReliefVault;
  waitForDeployment(): Promise<this>;

  interface: ShieldedReliefVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accumulateCrisis: TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  accumulateStandard: TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  saveMyEncryptedMemo: TypedContractMethod<
    [noteExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  viewEncryptedCrisisTotal: TypedContractMethod<[], [string], "view">;

  viewEncryptedStandardTotal: TypedContractMethod<[], [string], "view">;

  viewEncryptedUserMemo: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accumulateCrisis"
  ): TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "accumulateStandard"
  ): TypedContractMethod<
    [valueExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "saveMyEncryptedMemo"
  ): TypedContractMethod<
    [noteExt: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewEncryptedCrisisTotal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "viewEncryptedStandardTotal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "viewEncryptedUserMemo"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;

  filters: {};
}
