type ContractInfo = { abi: any[]; address?: `0x${string}`; chainId?: number; chainName?: string };

// Placeholder ABI fragments (only methods we call). Real ABIs should be generated by scripts/genabi.mjs after deploy.
const ReliefTreasuryABI = [
  { type: "function", name: "contribute", inputs: [ { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "crisis", type: "bool" } ], outputs: [] },
  { type: "function", name: "queryBalances", inputs: [ { name: "token", type: "address" } ], outputs: [ { type: "uint256", name: "normal" }, { type: "uint256", name: "crisis" } ], stateMutability: "view" },
];
const ShieldedReliefVaultABI = [
  { type: "function", name: "viewEncryptedStandardTotal", inputs: [], outputs: [ { type: "bytes32" } ], stateMutability: "view" },
  { type: "function", name: "viewEncryptedCrisisTotal", inputs: [], outputs: [ { type: "bytes32" } ], stateMutability: "view" },
  { type: "function", name: "viewEncryptedUserMemo", inputs: [ { name: "user", type: "address" } ], outputs: [ { type: "bytes32" } ], stateMutability: "view" },
  { type: "function", name: "accumulateStandard", inputs: [ { type: "bytes32" }, { type: "bytes" } ], outputs: [] },
  { type: "function", name: "accumulateCrisis", inputs: [ { type: "bytes32" }, { type: "bytes" } ], outputs: [] },
  { type: "function", name: "saveMyEncryptedMemo", inputs: [ { type: "bytes32" }, { type: "bytes" } ], outputs: [] },
];

// Minimal Governance ABI used by the UI (read + simple interactions)
const CrisisCouncilABI = [
  { type: "function", name: "submitResolution", inputs: [
      { name: "recipient", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "purposeCID", type: "string" },
      { name: "duration", type: "uint256" },
      { name: "emergency", type: "bool" },
      { name: "fromCrisisPool", type: "bool" }
    ], outputs: [ { type: "uint256" } ], stateMutability: "nonpayable" },
  { type: "function", name: "nextResolutionId", inputs: [], outputs: [ { type: "uint256" } ], stateMutability: "view" },
  { type: "function", name: "resolutions", inputs: [ { name: "id", type: "uint256" } ], outputs: [
      { name: "id", type: "uint256" },
      { name: "proposer", type: "address" },
      { name: "recipient", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "purposeCID", type: "string" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "emergency", type: "bool" },
      { name: "fromCrisisPool", type: "bool" }
    ], stateMutability: "view" },
  { type: "function", name: "supportWeight", inputs: [ { type: "uint256" } ], outputs: [ { type: "uint256" } ], stateMutability: "view" },
  { type: "function", name: "againstWeight", inputs: [ { type: "uint256" } ], outputs: [ { type: "uint256" } ], stateMutability: "view" },
  { type: "function", name: "castVote", inputs: [ { name: "id", type: "uint256" }, { name: "support", type: "bool" }, { name: "oneExt", type: "bytes32" }, { name: "inputProof", type: "bytes" } ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "finalizeOutcome", inputs: [ { name: "id", type: "uint256" } ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "closeEarly", inputs: [ { name: "id", type: "uint256" } ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "executeResolution", inputs: [ { name: "id", type: "uint256" } ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getEncryptedTallies", inputs: [ { name: "id", type: "uint256" } ], outputs: [ { type: "bytes32" }, { type: "bytes32" } ], stateMutability: "view" },
  { type: "function", name: "grantDecryption", inputs: [ { name: "id", type: "uint256" }, { name: "viewer", type: "address" } ], outputs: [], stateMutability: "nonpayable" },
];

// This map will be overridden by genabi output after deployments
const ADDRESSES: Record<string, { address: `0x${string}`; chainId: number; chainName: string }> = {
  "11155111:ReliefTreasury": {
    "address": "0xfFEbF9A138575CB9693ae6a260D3d317A4Db6271",
    "chainId": 11155111,
    "chainName": "sepolia"
  },
  "11155111:CrisisCouncil": {
    "address": "0x3557650E12BD8ADf36401aD4fCD0199ac004305b",
    "chainId": 11155111,
    "chainName": "sepolia"
  },
  "11155111:RecipientDirectory": {
    "address": "0xE75B02e93bBB94dde978127B7291EB71a55691dB",
    "chainId": 11155111,
    "chainName": "sepolia"
  },
  "11155111:ShieldedReliefVault": {
    "address": "0x405B750c05b0f26e8eFdAb8eD71e03Fbc8266468",
    "chainId": 11155111,
    "chainName": "sepolia"
  }
};

function key(name: string, chainId?: number) { return `${chainId ?? ""}:${name}`; }

export const contractsMap = {
  getContract(name: "ReliefTreasury" | "ShieldedReliefVault" | "CrisisCouncil" | "RecipientDirectory", chainId?: number): ContractInfo | undefined {
    const entry = ADDRESSES[key(name, chainId) as keyof typeof ADDRESSES];
    const common = { chainId, chainName: entry?.chainName } as any;
    if (name === "ReliefTreasury") return { abi: ReliefTreasuryABI as any[], address: entry?.address, ...common };
    if (name === "ShieldedReliefVault") return { abi: ShieldedReliefVaultABI as any[], address: entry?.address, ...common };
    if (name === "CrisisCouncil") return { abi: CrisisCouncilABI as any[], address: entry?.address, ...common };
    return { abi: [], address: entry?.address, ...common };
  },
};


